# ------------------------------------------------------------
# This is the initial script to generate the plots of
# high correlation counts data generated by the 
# correlation.matrix.Nov7.R script.
# ------------------------------------------------------------
setwd("/home/bmb191/math5376D/Final.Project")

# ------------------------------------------------------------
# Load in data
# ------------------------------------------------------------
alive_normal <- read.table(
  "Output.Files/alive.normal.corr.matrix.txt",
  header=F)
alive_tumor <- read.table(
  "Output.Files/alive.tumor.corr.matrix.txt",
  header=F)
dead_normal <- read.table(
  "Output.Files/dead.normal.corr.matrix.txt",
  header=F)
dead_tumor <- read.table(
  "Output.Files/dead.tumor.corr.matrix.txt",
  header=F)

# ------------------------------------------------------------
# Function to get each row's high correlation count
# param: corr_matrix - The correlation matrix we choose to 
# calculate the counts for.
# ------------------------------------------------------------
# get counts for each row alive matrix with |corr|>.8
high_corr_counts <- function(corr_matrix) {
  apply(corr_matrix, 1, function(x) sum(abs(x)>.8))
}

# ------------------------------------------------------------
# Remove duplicate entries on corr matrix.
# Feedback from Dr. Sun: We should not do this for 
# correlation pairs.
# ------------------------------------------------------------
# alive_tumor[lower.tri(alive_tumor,diag=TRUE)] <- 0
# alive_normal[lower.tri(alive_normal,diag=TRUE)] <- 0
# dead_tumor[lower.tri(dead_tumor,diag=TRUE)] <- 0
# dead_normal[lower.tri(dead_normal,diag=TRUE)] <- 0

# ------------------------------------------------------------
# Get high correlation counts for each dataset
# ------------------------------------------------------------
alive_tumor_high_corr_cnts <- high_corr_counts(alive_tumor)
alive_normal_high_corr_cnts <- high_corr_counts(alive_normal)
dead_tumor_high_corr_cnts <- high_corr_counts(dead_tumor)
dead_normal_high_corr_cnts <- high_corr_counts(dead_normal)

# ------------------------------------------------------------
# Write each result to a table
# ------------------------------------------------------------
write.table(
  alive_tumor_high_corr_cnts, 
  "Output.Files/alive.tumor.high.corr.cnts.txt", 
  row.names=FALSE, 
  col.names=FALSE
)
write.table(
  alive_normal_high_corr_cnts, 
  "Output.Files/alive.normal.high.corr.cnts.txt", 
  row.names=FALSE, 
  col.names=FALSE
)
write.table(
  dead_tumor_high_corr_cnts, 
  "Output.Files/dead.tumor.high.corr.cnts.txt", 
  row.names=FALSE, 
  col.names=FALSE
)
write.table(
  dead_normal_high_corr_cnts, 
  "Output.Files/dead.normal.high.corr.cnts.txt", 
  row.names=FALSE, 
  col.names=FALSE
)

# ------------------------------------------------------------
# Five number summary statistics for each data set.
# ------------------------------------------------------------
fivenum(alive_tumor_high_corr_cnts)
fivenum(alive_normal_high_corr_cnts)
fivenum(dead_tumor_high_corr_cnts)
fivenum(dead_normal_high_corr_cnts)

# ------------------------------------------------------------
# Data visualization - We want to see the density plot for
# each correlation count distribution to compare the tumor
# vs. the normal data.
# ------------------------------------------------------------
# Alive data
# ------------------------------------------------------------
plot(
  density((alive_tumor_high_corr_cnts)^(1/4)),
  col="blue",
  main="Alive High Correlation Count Density",
  xlim=c(0,3),
  ylim=c(0,4)
)
legend("topright", legend=c("Tumor","Normal"), fill=c("blue","red"))
lines(
  density((alive_normal_high_corr_cnts)^(1/4)),
  col="red"
)
# ------------------------------------------------------------
# Dead data
# ------------------------------------------------------------
plot(
  density((dead_tumor_high_corr_cnts)^(1/4)),
  col="blue",
  main="Dead High Correlation Count Density",
  xlim=c(0,3),
  ylim=c(0,4)
)
legend("topright", legend=c("Tumor","Normal"), fill=c("blue","red"))
lines(
  density((dead_normal_high_corr_cnts)^(1/4)),
  col="red"
)

# ------------------------------------------------------------
# Plot histogram for the dead data
# ------------------------------------------------------------
hist((dead_tumor_high_corr_cnts)^(1/4), breaks=20, col="red")
hist((dead_normal_high_corr_cnts)^(1/4), breaks=20, col="blue", add=TRUE)
